M48
; DRILL file {KiCad (7.0.0)} date Sun Oct 22 09:50:10 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-22T09:50:10+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.180
%
G90
G05
T1
X119.67Y-98.5
X119.67Y-101.5
T2
X121.25Y-106.8
X121.25Y-112.8
T0
M30
